### PR TITLE
Configure one of the tests to use C++14

### PR DESCRIPTION
**Pull request by nargeslein**
Hi @k06a,
I have addressed issue #54 by creating a separate test target which requires C++14 and changes to the CMake files.
In addition I have added a comment in the README.

I hope this addresses the issue as you had expected and I am looking forward to further contributions. It was really interesting to work on this so far.

### CODE REVIEW

**Comment by k06a** [comment]
Hi @nargeslein! Thanks for the contribution. I wonder why CI is not even started for this PR…

**Comment by k06a** [comment]
@nargeslein please use branch with name other than `master` next time, it will be much more convenient 👍

**Comment by nargeslein** [comment]
> @nargeslein please use branch with name other than `master` next time, it will be much more convenient +1

Hi @k06a many thanks for the feedback. I will use a branch next time. Do you have an idea/suggestion for the naming?

**Comment by k06a** [comment]
Use something like this next time.
```
feature/cpp14-test
test/cpp14
```

This time I will merge it once we will fix CI issues :)

**Comment by nargeslein** [comment]
> Use something like this next time.
> 
> ```
> feature/cpp14-test
> test/cpp14
> ```
> 
> This time I will merge it once we will fix CI issues :)

I have renamed the branch 'master' to 'feature/cpp14-test' in any case but not sure if it will be picked up in this PR

**Pull request merged**
