### PR TITLE
improving the performance of "take": it won't any longer iterate through...

### PR DESCRIPTION
**Pull request by parallaxe**
... the whole sequence, only the items it needs to

### CODE REVIEW

**Comment by k06a** [comment]
Looks like first version:
```
return where_i([=](T, int i){return i < count;});
```
does not contains enumeration too. It just returns smart enumerator with simple predicate.

**Comment by parallaxe** [comment]
Yes, but when the enumerator is used, it will enumerate more than it has to.
Given the code-snippet

```
#include <iostream>
#include <vector>
#include <list>
#include <boolinq/boolinq.h>

using namespace std;
using namespace boolinq;
int main(int argc, char *argv[]) {
	int mugi[] = {1,2,3,4};
	
	auto result = from(mugi)
	.where([](int a) { cout << "iterate " << a << endl; return true;})
	.take(1)
	.toList();
}
```
i would expect that it only writes "iterate 1" to stdout and than breaking the enumeration. Instead, it writes
```
iterate 1
iterate 2
iterate 3
iterate 4
```
that shows that it iterates through the whole sequence. My patch reduces it and will only write the expected "iterate 1". I think this is be a huge performance-gain when take is used on a large sequence and complex queries.

**Comment by k06a** [comment]
Oh, yep. I agree this is significant improvement. Maybe it will be shorter to add `if (i == count) throw ...` inside `where_i`?

**Comment by k06a** [comment]
Or use `select_i` with code:
```
if (i == count)
    throw …
return en.nextObject();
```

**Comment by parallaxe** [comment]
Haven't thought of this, i agree that using where_i / select_i would be more. As you said, the version with where_i may look like
```
return where_i([=](T a, int i){
	if(i == count)
		throw EnumeratorEndException();
	return a;
});
```
and would work well (= the tests pass), but it will iterate one time more than my version does. Although, given the better readability, i would prefer the where_i-solution.
I'm not sure about your suggestion with select_i by using en.nextObject() - does en refer to the _enumerator-object inside the current LinqObj-instance? Then it won't work as nextObject() isn't a const-function and can't be called inside take (it may be possible by some tricks/hacks, but the readability would suffer) - or maybe I'm missing the point here?

For now, i update the patch to use the where_i-version.

**Comment by k06a** [comment]
`where_i` predicate should return `true` Instead of `a`. Or this should be `select_i`. My words about `en` - were mistake, sure `a ` should be returned.

**Comment by k06a** [comment]
@parallaxe thanks for this improvement :+1:

**Pull request merged**
