### PR TITLE
Add different versions of C++ to CI

### PR DESCRIPTION
**Pull request by Xav83**
Hi @k06a,

I am creating this Pull Request to start setting up GitHub Actions in relation with the issue #63. :slightly_smiling_face: 

For now, this Pull Request only has a simple GitHub Actions workflow to run the `boolinq-test`, to make sure that it works.
I am going update it later, in order to solve completely the issue #63.

### CODE REVIEW

**Comment by k06a** [comment]
Hi, @Xav83!

- Let's have all targets as separate actions
- And let's try to compile library with different compilers please

**Comment by Xav83** [comment]
Hi again @k06a, :slightly_smiling_face: 

I have added a new commit which makes GitHub Actions compile the library with all the compilers available in the Ubuntu environment provided by GitHub Actions. Those compilers are:
- GNU 9.4.0
- GNU 10.3.0
- Clang 10.0.0
- Clang 11.0.0
- Clang 12.0.0

So, at the moment, this Pull Request set up GitHub Action to compile the library with all those compilers, and for each of them, it compiles with each C++ version requested in #63 (C++11, C++14, C++17, C++20). And finally, after each of this compilation, GitHub Actions runs the executable `boolinq-test`. :tada: 

I have now 2 new questions:
- Do you want some other compiler version to be tested? It is probably possible to install more `gcc` and `clang` versions if you need some specific versions.
- When you say that you want "have all targets as separate actions", I need more detail about what exactly you need, in order to set up GitHub Actions correctly for you. Do you need to have `boolinq-test`, `boolinq-test14` and `boolinq-bench` to be runned for each configuration (for each compiler and each C++ version) ? Or running them for only one configuration is enough (Clang 12.0.0 and C++20, for example) ?

**Comment by Xav83** [comment]
*Note:* It seems that GitHub Actions may not be activated on you repository. For now, I am currently testing that it works correctly on a [Pull Request on my own fork ](https://github.com/Xav83/boolinq/pull/1) :wink:

**Comment by k06a** [comment]
Great job @Xav83!

**Review by k06a — APPROVED** [review]

**Comment by k06a** [comment]
@Xav83 I see issues with the CI: https://github.com/k06a/boolinq/actions/runs/3990591651/jobs/6844419648#step:3:22

**Pull request merged**
